# Generated by Django 5.2.3 on 2025-07-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_chathistory_chathistorycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistorycontent',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
