# Generated by Django 5.2.3 on 2025-07-02 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistorycontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
