# Generated by Django 5.1.11 on 2025-09-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_article_test_alani_alter_chathistorycontent_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default-image.png", null=True, upload_to="media/"
            ),
        ),
    ]
