# Generated by Django 6.0 on 2026-01-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_notification_psychologistmessage_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('psychologist', 'Psychologist')], default='member', max_length=20),
        ),
    ]
