# Generated by Django 6.0.3 on 2026-03-16 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_loginactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='life_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('very_good', 'Çok iyi'), ('good', 'İyi'), ('neutral', 'Nötr'), ('bad', 'Kötü'), ('very_bad', 'Çok kötü')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=280, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='articles_da_user_id_d87aea_idx'), models.Index(fields=['date'], name='articles_da_date_c2b025_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
