# Generated by Django 6.0.3 on 2026-04-02 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_profile_life_story_dailymood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('acil', 'Acil'), ('supheli', 'Şüpheli'), ('normal', 'Normal')], default='normal', max_length=20, verbose_name='Kategori')),
                ('private_notes', models.TextField(blank=True, null=True, verbose_name='Kişiye Özel Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_users', to=settings.AUTH_USER_MODEL, verbose_name='Psikolog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_relations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Psikolog-Kullanıcı İlişkisi',
                'verbose_name_plural': 'Psikolog-Kullanıcı İlişkileri',
                'ordering': ['-updated_at'],
                'unique_together': {('psychologist', 'user')},
            },
        ),
    ]
