# Generated by Django 6.0.6 on 2026-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_psychologistuserrelation_category_forumpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychologistmessage',
            name='encrypted_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychologistmessage',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
