from django.urls import path
from . import views

urlpatterns = [
    path("", views.my_login, name=""),
    path("register", views.register, name="register"),
    path("register/", views.register, name="register"),
    path("my-login", views.my_login, name="my-login"),
    path("my-login/", views.my_login, name="my-login"),
    path("psychologist-login", views.psychologist_login, name="psychologist-login"),
    path("psychologist-login/", views.psychologist_login, name="psychologist-login"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("llm_api/stream", views.stream_llm_response, name="llm_stream"),
    path("user-logout", views.user_logout, name="user-logout"),
    path("create-article", views.create_article, name="create-article"),
    path("my-articles", views.my_articles, name="my-articles"),
    path("update-article/<str:pk>", views.update_articles, name="update-article"),
    path("delete-article/<str:pk>", views.delete_articles, name="delete-article"),
    path("profile-management", views.profile_management, name="profile-management"),
    path("delete-account", views.delete_account, name="delete-account"),
    path("acil-destek", views.acil_destek, name="acil-destek"),
    path("gunluk-kartlar", views.gunluk_kartlar, name="gunluk-kartlar"),
    path("destek-duvari", views.destek_duvari, name="destek-duvari"),
    path("haftalik-raporlar", views.haftalik_raporlar, name="haftalik-raporlar"),
    path("bildirimler", views.bildirimler, name="bildirimler"),
    path("settings", views.settings_view, name="settings"),
    path("help-center", views.help_center, name="help-center"),
    path("update-password/", views.update_password, name="update-password"),
    path("contact", views.contact, name="contact"),
    path("upload-photo/", views.upload_photo, name="upload-photo"),
    path("anasayfa", views.anasayfa, name="anasayfa"),
    path("meditasyon", views.meditasyon, name="meditasyon"),
    path("meditasyon/<str:audio_id>", views.meditasyon_audio, name="meditasyon-audio"),
    path("nefes-egzersizi", views.nefes_egzersizi, name="nefes-egzersizi"),
    path('responsive.html', views.responsive, name='responsive'),
    path('like/', views.like_story, name='like_story'),
    path('check-availability', views.check_availability, name='check-availability'),
    # Psikolog sistemi URL'leri
    path('psychologist-dashboard', views.psychologist_dashboard, name='psychologist-dashboard'),
    path('psychologist-chat/<int:user_id>', views.psychologist_chat, name='psychologist-chat'),
    path('api/send-task/', views.send_task, name='send-task'),
    path('api/send-notification/', views.send_notification, name='send-notification'),
    path('api/send-psychologist-message/', views.send_psychologist_message, name='send-psychologist-message'),
    path('api/send-user-message/', views.send_user_message, name='send-user-message'),
    path('api/get-psychologist-messages/', views.get_psychologist_messages, name='get-psychologist-messages'),
    path('api/get-user-messages/', views.get_user_messages, name='get-user-messages'),
    path('api/get-user-tasks/', views.get_user_tasks, name='get-user-tasks'),
    path('api/member/tasks/', views.get_user_tasks, name='get-member-tasks'),  # Alias for consistency
    path('api/get-user-notifications/', views.get_user_notifications, name='get-user-notifications'),
    path('api/unread-counts/', views.get_unread_counts, name='get-unread-counts'),
    path('api/unread-message-count/', views.get_unread_message_count, name='get-unread-message-count'),
    path('api/mark-messages-read/', views.mark_messages_read, name='mark-messages-read'),
    path('api/mark-psychologist-messages-read/', views.mark_psychologist_messages_read, name='mark-psychologist-messages-read'),
    path('api/member/badges/', views.get_member_badges, name='get-member-badges'),
    path('api/member/mark-notifications-read/', views.mark_notifications_read, name='mark-notifications-read'),
    path('api/member/stats/', views.get_member_stats, name='get-member-stats'),
]
